# DEPRECATED: Legacy data preparation script from Openmind era.
# The current Processing pipeline (Processing/*/Pipeline/) supersedes this.
# Paths may still reference decommissioned Openmind directories.
#
import synapseclient
from synapseutils import syncFromSynapse


# login to synapse
syn = synapseclient.Synapse()
syn.login(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZy9hdXRoL3YxIiwiYXVkIjoiMCIsIm5iZiI6MTc1NTgxNzc0NiwiaWF0IjoxNzU1ODE3NzQ2LCJqdGkiOiIyNDkwMiIsInN1YiI6IjM0OTYxNTMifQ.EkBeYbdAMyO12L-uA5cOaFuPIrWzriMiWZle9Pb_9umKGJ9In0fl1qoB-ZpvUaYkMz7_kcxETQMRO5Ba5DqUXoj92OQHaC6TRpbjt-vjabxJDWCwPJ0zimJu4Rxe-VljjIOkRvLrPOXNMTSbExLz6dBaEXVANUMhV5IFXHYnQjtjyVOGGjWZNza-rsBwxXGLjaeGJwd6eCXCLG-yS0nwaI9vUZf3icZlJeir0iSucCuOIGF9wIdDHNMUVaSBE1yxEzbr7edNvsz83yiRKZjoA2n2IRawvRFv_ffhoJCvWKC_KCiumFvzFEi15-HmS_0-wSdePKA8SPtcqr1VzDXcpw")

syncFromSynapse(syn, entity="syn53693961", path="/om/scratch/Mon/mabdel03/SocialIsolation/")
