name: single_cell_BP
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base>=4.2
  - r-ggplot2
  - bioconductor-biocparallel
  - bioconductor-genomeinfodbdata
  - bioconductor-singlecellexperiment
  - bioconductor-scdblfinder
  - bioconductor-zellkonverter
