#!/bin/bash
#
# Path Configuration for ROSMAP snRNA-seq Pipeline
# Edit these paths to match your cluster environment.
#
# This file is the SINGLE SOURCE OF TRUTH for all paths used across the
# pipeline.  Every shell wrapper should `source` it rather than hard-coding
# paths.  See config/README.md for setup instructions.
#

# =============================================================================
# AUTO-DETECTED PATHS (no edits needed)
# =============================================================================

# Repository root — derived from this file's location (config/ is one level
# below the repo root).  Works regardless of where the repo is cloned.
_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export REPO_ROOT="$(cd "${_CONFIG_DIR}/.." && pwd)"

# Workspace root — the parent of the repo, where large data directories live
# (e.g. Tsai_Data/).
export WORKSPACE_ROOT="$(cd "${REPO_ROOT}/.." && pwd)"

# =============================================================================
# CONDA CONFIGURATION
# =============================================================================

# Conda initialization script — update this to your conda/mamba installation:
#   miniconda:  ~/miniconda3/etc/profile.d/conda.sh
#   miniforge:  ~/miniforge3/etc/profile.d/conda.sh
#   anaconda:   ~/anaconda3/etc/profile.d/conda.sh
export CONDA_INIT_SCRIPT="/om2/user/mabdel03/anaconda/etc/profile.d/conda.sh"

# Base conda environment directory
export CONDA_ENV_BASE="/om2/user/mabdel03/conda_envs"

# Specific environments
export CELLBENDER_ENV="/om2/user/mabdel03/conda_envs/Cellbender_env"
export SYNAPSE_ENV="${CONDA_ENV_BASE}/synapse_env"
export PYTHON_ENV="${CONDA_ENV_BASE}/python_env"
export SINGLECELL_ENV="${CONDA_ENV_BASE}/single_cell_BP"
export BATCHCORR_ENV="${CONDA_ENV_BASE}/BatchCorrection_SingleCell"
export QC_ENV="/om2/user/mabdel03/conda_envs/qcEnv"

# =============================================================================
# BASE DATA PATHS
# =============================================================================

# Permanent storage (home/project directory)
export DATA_ROOT="/orcd/data/lhtsai/001/om2/mabdel03/files/ACE_Analysis"

# Scratch/temporary storage (Openmind scratch)
export SCRATCH_ROOT="/om/scratch/Mon/mabdel03"

# =============================================================================
# REFERENCE DATA
# =============================================================================

# Cell Ranger reference transcriptome
export CELLRANGER_REF="/om2/user/mabdel03/yard/references/human/refdata-gex-GRCh38-2020-A"

# Cell Ranger executable
export CELLRANGER_PATH="/om2/user/mabdel03/apps/yard/cellranger-8.0.0"

# =============================================================================
# DEJAGER DATA PATHS
# =============================================================================

# Input FASTQs (downloaded from Synapse)
export DEJAGER_FASTQS="${SCRATCH_ROOT}/FASTQs"

# Cell Ranger output counts
export DEJAGER_COUNTS="${SCRATCH_ROOT}/Counts"

# Preprocessed counts (CellBender output) - permanent storage
export DEJAGER_PREPROCESSED="${DATA_ROOT}/Data/DeJager/Preprocessed_Counts"

# =============================================================================
# DEJAGER DEMUXLET PATHS
# =============================================================================

# WGS data directory (filtered BAMs, pileups, demuxlet outputs)
export DEJAGER_WGS_DIR="/om/scratch/Mon/shared_folder/WGS"

# SNP VCF for demuxlet (SNP-only, concatenated, lifted to GRCh38, ~84GB)
export DEJAGER_DEMUX_VCF="${DEJAGER_WGS_DIR}/snp_fixedconcatenated_liftedROSMAP.vcf.gz"

# Demuxafy Singularity container
export DEMUXAFY_SIF="${DEJAGER_WGS_DIR}/Demuxafy.sif"

# Per-library patient ID files
export DEJAGER_PATIENT_IDS_DIR="${DEJAGER_WGS_DIR}/individ"

# Bcftools conda environment (for BAM filtering)
export BCFTOOLS_ENV="/net/vast-storage/scratch/vast/lhtsai/mabdel03/conda_envs/bcftools_env"

# Singularity module
export SINGULARITY_MODULE="openmind/singularity/3.10.4"

# =============================================================================
# TSAI DATA PATHS
# =============================================================================

# Tsai FASTQs CSV (generated by Preprocessing/Tsai/01_FASTQ_Location pipeline)
export TSAI_FASTQS_CSV="${DATA_ROOT}/Data/Tsai/Preprocessing/FASTQ_Transfer/New/CSVs/All_ROSMAP_FASTQs.csv"

# Tsai FASTQs (Openmind transfer destination)
export TSAI_FASTQS_DIR="${SCRATCH_ROOT}/Tsai_Data/FASTQs"

# Cell Ranger output (per projid)
export TSAI_CELLRANGER_OUTPUT="${SCRATCH_ROOT}/Tsai_Data/Cellranger_Outputs"

# Temporary Cell Ranger output (scratch - deleted after CellBender)
export TSAI_CELLRANGER_SCRATCH="${TSAI_CELLRANGER_OUTPUT}"

# Temporary CellBender output (scratch - copied to permanent then deleted)
export TSAI_CELLBENDER_SCRATCH="${SCRATCH_ROOT}/Tsai/Cellbender_Output"

# Preprocessed counts (CellBender output — used as input to Processing pipeline)
export TSAI_PREPROCESSED="${WORKSPACE_ROOT}/Tsai_Data/Cellbender_Outputs"

# Legacy cohort-specific paths (for reference)
export TSAI_COUNTS_ACE="${SCRATCH_ROOT}/Tsai/ACE/Counts"
export TSAI_COUNTS_RESILIENT="${SCRATCH_ROOT}/Tsai/Resilient/Counts"
export TSAI_COUNTS_SOCISL="${SCRATCH_ROOT}/Tsai/SocIsl/Counts"

# =============================================================================
# TSAI PROCESSING PIPELINE PATHS
# =============================================================================

# Base output directory for the three-stage processing pipeline
export TSAI_PROCESSING_OUTPUTS="${WORKSPACE_ROOT}/Tsai_Data/Processing_Outputs"

# Per-stage I/O directories
export TSAI_QC_FILTERED="${TSAI_PROCESSING_OUTPUTS}/01_QC_Filtered"
export TSAI_DOUBLET_REMOVED="${TSAI_PROCESSING_OUTPUTS}/02_Doublet_Removed"
export TSAI_INTEGRATED="${TSAI_PROCESSING_OUTPUTS}/03_Integrated"

# SLURM log directory
export TSAI_PROCESSING_LOGS="${TSAI_PROCESSING_OUTPUTS}/Logs"

# Patient metadata (tracked in repo)
export TSAI_METADATA_CSV="${REPO_ROOT}/Preprocessing/Tsai/02_Cellranger_Counts/Tracking/patient_metadata.csv"

# Marker reference for ORA annotation (tracked in repo)
export TSAI_MARKERS_RDS="${REPO_ROOT}/Processing/Tsai/Pipeline/Resources/Brain_Human_PFC_Markers_Mohammadi2020.rds"

# =============================================================================
# DEJAGER PROCESSING PIPELINE PATHS
# =============================================================================

# Base output directory for the three-stage processing pipeline
export DEJAGER_PROCESSING_OUTPUTS="${WORKSPACE_ROOT}/DeJager_Data/Processing_Outputs"

# Per-stage I/O directories
export DEJAGER_QC_FILTERED="${DEJAGER_PROCESSING_OUTPUTS}/01_QC_Filtered"
export DEJAGER_DOUBLET_REMOVED="${DEJAGER_PROCESSING_OUTPUTS}/02_Doublet_Removed"
export DEJAGER_INTEGRATED="${DEJAGER_PROCESSING_OUTPUTS}/03_Integrated"

# SLURM log directory
export DEJAGER_PROCESSING_LOGS="${DEJAGER_PROCESSING_OUTPUTS}/Logs"

# Patient barcode-to-ID mapping CSV (shared resource)
export DEJAGER_PATIENT_MAP="/om/scratch/Mon/shared_folder/WGS/cell_to_patient_assignmentsFinal0.csv"

# Patient ID overrides for "alone" libraries (JSON)
export DEJAGER_PATIENT_ID_OVERRIDES="${REPO_ROOT}/Processing/DeJager/Pipeline/Resources/patient_id_overrides.json"

# Marker reference for ORA annotation (shared with Tsai)
export DEJAGER_MARKERS_RDS="${REPO_ROOT}/Processing/Tsai/Pipeline/Resources/Brain_Human_PFC_Markers_Mohammadi2020.rds"

# =============================================================================
# PHENOTYPE / CLINICAL DATA (tracked in repo)
# =============================================================================

export PHENOTYPE_DIR="${REPO_ROOT}/Data/Phenotypes"
export ROSMAP_CLINICAL_CSV="${PHENOTYPE_DIR}/ROSMAP_clinical.csv"
export ACE_SCORES_CSV="${PHENOTYPE_DIR}/TSAI_DEJAGER_all_patients_wACEscores.csv"
export DEJAGER_ID_MAP="${PHENOTYPE_DIR}/DeJager_ID_Map.csv"

# =============================================================================
# SLURM SETTINGS
# =============================================================================

# Email for SLURM job notifications (leave empty to disable)
export SLURM_MAIL_USER="mabdel03@mit.edu"

# Default SLURM partition (leave empty for cluster default)
export SLURM_PARTITION=""

# =============================================================================
# FASTQ TRANSFER PIPELINE PATHS (Tsai)
# =============================================================================

# Root directory for the FASTQ transfer pipeline outputs
export TSAI_FASTQ_TRANSFER_ROOT="${DATA_ROOT}/Data/Tsai/Preprocessing/FASTQ_Transfer"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

# Initialize conda
init_conda() {
    source "${CONDA_INIT_SCRIPT}"
}

# Activate a conda environment by full path
activate_env() {
    local env_path="$1"
    init_conda
    conda activate "${env_path}"
}

# Verify paths exist
check_paths() {
    local errors=0
    echo "Checking required paths..."

    if [[ ! -d "${DATA_ROOT}" ]]; then
        echo "ERROR: DATA_ROOT does not exist: ${DATA_ROOT}"
        errors=$((errors + 1))
    fi

    if [[ "${SCRATCH_ROOT}" == "/path/to/your/scratch" ]]; then
        echo "WARNING: SCRATCH_ROOT is not configured. Update config/paths.sh"
        errors=$((errors + 1))
    fi

    if [[ ! -f "${CONDA_INIT_SCRIPT}" ]]; then
        echo "ERROR: Conda init script not found: ${CONDA_INIT_SCRIPT}"
        errors=$((errors + 1))
    fi

    if [[ ! -f "${CELLRANGER_PATH}/cellranger" ]]; then
        echo "WARNING: Cell Ranger executable not found: ${CELLRANGER_PATH}/cellranger"
    fi

    if [[ ! -d "${CELLRANGER_REF}" ]]; then
        echo "WARNING: Cell Ranger reference not found: ${CELLRANGER_REF}"
    fi

    if [[ ${errors} -gt 0 ]]; then
        echo "FAILED: ${errors} critical path(s) missing."
        return 1
    fi

    echo "All paths verified."
    return 0
}

# =============================================================================
# LOCAL OVERRIDES (optional)
# =============================================================================
# To customize paths without modifying this tracked file, create
# config/paths.local.sh and override any variables there.  That file
# is listed in .gitignore and will never be committed.
if [[ -f "${_CONFIG_DIR}/paths.local.sh" ]]; then
    source "${_CONFIG_DIR}/paths.local.sh"
fi

