name: nebulaAnalysis7
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0
  - numpy>=1.24
  - scipy>=1.10
  - h5py>=3.8
  - r-base>=4.2
  - r-dplyr
  - bioconductor-zellkonverter
  - bioconductor-deseq2
  - bioconductor-singlecellexperiment
  - bioconductor-scran
  - pip
  - pip:
      - anndata>=0.9
